# @package _global_
dataset:
#  _target_: src.data.MIMIC3RealDatasetCollection       # Will be dynamically instantiated
  seed: ${exp.seed}
  name: gsu
#  path: data/processed/all_hourly_data.h5              # Path with MIMIC-3 dataset (HDFStore)
  min_seq_length: 71                                  # Min sequence length in cohort
  max_seq_length: 71                                   # Max sequence length in cohort
  max_number: 5000                                     # Maximum number of patients in cohort
  projection_horizon: 0                                # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
#  split:
#    val: 0.15
#    test: 0.15
  val_batch_size: 512                                  # Batch size for evaluation
  treatment_mode: multilabel
  autoregressive: True

  treatment_list: ???
  outcome_list: ???
  vital_list: ???
  static_list: ???
  drop_first: False                                     # One-hot encoding of categorical static features

exp:
  unscale_rmse: True
  percentage_rmse: False
